# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  # password: PASSWORD
  host: localhost

development:
  <<: *default
  database: asagao_development

test:
  <<: *default
  database: asagao_test

production:
  <<: *default
  database: asagao_production
